spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8882
          predicates:
            - Path=/api/user/**,/api/auth/**,/public/avatars/**
        - id: story-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/story/**,/public/images/**
        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payment/**
        - id: comment-service
          uri: http://localhost:8883
          predicates:
            - Path=/api/comment/**,/api/comments/**,/api/reaction/**,/api/rating/**
        - id: notification-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/notification/**
        - id: admin-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/admin/**
        - id: analystic-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/analytics/**
        - id: search-recommendation-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/search/**,/api/recommendation/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

  docker:
    compose:
      enabled: false

server:
  port: 8081

jwt:
  secret: mySuperSecretKeyForJwtAuth1234567890
